name=EDP-Platform-Arduino
version=0.1.0
author=Simon J. Stuart
maintainer=Simon J. Stuart
sentence=Arduino framework backend implementations and Arduino-owned ESPressio integrations.
paragraph=Concrete Arduino-environment Platform capabilities plus optional Arduino-owned integrations such as conversion between Arduino String and EDP-BoundedTypes String.
category=Other
url=https://espressio.org
architectures=*
includes=ESPressio_Platform_Arduino.hpp
depends=EDP-Platform (>=0.1.0 && <0.2.0)
