name=EDP-Platform-Arduino
version=0.1.0
author=Simon J. Stuart
maintainer=Simon J. Stuart
sentence=Arduino framework backend implementations for EDP-Platform.
paragraph=Concrete Arduino-environment implementations of ESPressio Platform capabilities, beginning with the lock-free AtomicWord32 concurrency provider.
category=Other
url=https://espressio.org
architectures=*
includes=ESPressio_Platform_Arduino.hpp
depends=EDP-Platform (>=0.1.0 && <0.2.0)
